version: "3"

services:
    proxy:
        image: nginx:1.23-alpine
        ports:
            - ${PORT}:80
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
        environment:
            TZ: Asia/Tokyo
